=== antanas-vasiliauskas/uni/schema.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="Sandėlis">
        <xs:complexType>
           <xs:sequence>
                 <xs:element name="Prekės">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="Prekė" maxOccurs="unbounded">
                            <xs:complexType>
                                <xs:sequence>
                                    <xs:element name="Pavadinimas" type="xs:string"/>
                                    <xs:element name="Kiekis">
                                        <xs:complexType>
                                            <xs:simpleContent>
                                                <xs:extension base="xs:decimal">
                                                    <xs:attribute name="vienetas" type="xs:string" use="required"/>
                                                </xs:extension>
                                            </xs:simpleContent>
                                        </xs:complexType>
                                    </xs:element>
                                    <xs:element name="Atvežimo_data" type="xs:date" minOccurs="0"/>
                                </xs:sequence>
                            </xs:complexType>
                        </xs:element>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
           </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== antanas-vasiliauskas/uni/schema.xml
<Sandėlis xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="schema.xsd">
    <Prekės>
        <Prekė>
            <Pavadinimas>Miltai</Pavadinimas>
            <Kiekis vienetas="kg">50000</Kiekis>
        </Prekė>
        <Prekė>
            <Pavadinimas>Kiaušiniai</Pavadinimas>
            <Kiekis vienetas="vnt">2000</Kiekis>
            <Atvežimo_data>2021-10-21</Atvežimo_data>
        </Prekė>
    </Prekės>
</Sandėlis>
